task: ISLR
data:
  model_name: vtn_one_modality
  base_url: data/VN_SIGN
  dataset_name: VN_SIGN
  temporal_stride: 2
  num_output_frames: 16
  transform_cfg:
    index_setting:
      - segment #train_p
      - pad #train_m
      - segment #test_p
      - pad #test_m
  vid_transform:
    IMAGE_SIZE: 224
    NORM_MEAN_IMGNET: [0.485, 0.456, 0.406]
    NORM_STD_IMGNET: [0.229, 0.224, 0.225]
  SHOULDER_DIST_EPSILON: 1.2
  WRIST_DELTA: 0.15
  label_folder: label_1_200
  data_type: 1_200_center_ord1
training:
  label_smoothing: 0
  device: cuda:2
  overwrite: true
  log_freq: 1
  experiment_name: "vtn_vn_sign_cls"
  model_dir: results/vtn/vn_sign
  random_seed: 42
  shuffle: True
  num_workers: 4
  prefetch_factor: 4
  batch_size: 4 #to-debug!
  total_epoch: 300 #to-debug!
  learning_rate: 0.0001
  save_checkpoints: true
  scheduler_factor: 0.1
  scheduler_patience: 5
  plot_loss: true
  plot_lr: true
  plot_acc: true
  criterion: ContrastiveLoss
  optimzer: Adam
  lr_scheduler: StepLR
  top_k: 5
  print_stats: true
  pretrained: true
  pretrained_model: checkpoints/vtn_one_modality/vtn_vn_sign_cls/last_checkpoints2.pth # contrastive checkpoints
  # pretrained_model: /mnt/disk1/anhnct/HAR/principal_har/checkpoints/vtn/vtn_transfer_for_cls/checkpoints.pth
  lr_step_size: 5
  gamma: 0.5
  num_accumulation_steps: 4
  patience: 10
  verbose: true
  delta: 0
  is_early_stopping: true
  gradient_clip_val: 1.0
  w_decay: 0
  log_train_step: true
  log_steps: 50
  evaluate_step: 250
  evaluate_strategy: epoch

inference:
  batch_size: 8
model:
  num_classes: 199
  num_heads: 8
  num_layers: 4
  embed_size: 512
  cnn: rn34
  freeze_layers: 0 # free layers in cnn
  dropout: 0.1
  training_type: cls